# Generated by Django 3.1.1 on 2020-11-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0008_tsne'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsne',
            name='perplexity',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
