# Generated by Django 3.1.1 on 2020-11-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0010_bmc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmc',
            name='subset',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
