# Generated by Django 3.0.3 on 2020-09-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_remove_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pos_in_a_article',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
