# Generated by Django 3.1.1 on 2020-10-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0006_stemfreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginFreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
