# Generated by Django 3.1.1 on 2020-11-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0007_originfreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tsne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_num', models.IntegerField()),
                ('dataset_name', models.CharField(max_length=200)),
                ('x_val', models.FloatField()),
                ('y_val', models.FloatField()),
                ('label', models.CharField(max_length=200)),
            ],
        ),
    ]
