# Generated by Django 3.1.1 on 2020-11-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0009_tsne_perplexity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bmc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('background', models.CharField(max_length=200)),
                ('methods', models.CharField(max_length=200)),
                ('results', models.CharField(max_length=200)),
                ('conclusion', models.CharField(max_length=200)),
            ],
        ),
    ]
