# Generated by Django 3.1.1 on 2020-12-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0011_bmc_subset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionInDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('origin_term', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BsbiBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('pos_in_a_article', models.ManyToManyField(to='search_engine.PositionInDoc')),
                ('position', models.ManyToManyField(to='search_engine.Article')),
            ],
        ),
    ]
