# Generated by Django 3.1.1 on 2020-12-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0013_bsbi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spimi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('pos_in_a_artcle', models.ManyToManyField(to='search_engine.PositionInDoc')),
            ],
        ),
    ]
